# Generated by Django 5.2.4 on 2025-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kilogram', 'Kilogram'), ('liter', 'Liter')], default='grams', max_length=20),
        ),
    ]
